/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as StaticRouteImport } from './routes/_static'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaticTermsOfServiceRouteImport } from './routes/_static/terms-of-service'
import { Route as StaticPrivacyRouteImport } from './routes/_static/privacy'
import { Route as StaticLp5RouteImport } from './routes/_static/lp5'
import { Route as StaticLp4RouteImport } from './routes/_static/lp4'
import { Route as StaticLp3RouteImport } from './routes/_static/lp3'
import { Route as StaticLp2RouteImport } from './routes/_static/lp2'
import { Route as StaticLp1RouteImport } from './routes/_static/lp1'
import { Route as StaticLpRouteImport } from './routes/_static/lp'
import { Route as StaticDuckerwebRouteImport } from './routes/_static/duckerweb'
import { Route as AuthedGhcardsRouteImport } from './routes/_authed/ghcards'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticRoute = StaticRouteImport.update({
  id: '/_static',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticTermsOfServiceRoute = StaticTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => StaticRoute,
} as any)
const StaticPrivacyRoute = StaticPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => StaticRoute,
} as any)
const StaticLp5Route = StaticLp5RouteImport.update({
  id: '/lp5',
  path: '/lp5',
  getParentRoute: () => StaticRoute,
} as any)
const StaticLp4Route = StaticLp4RouteImport.update({
  id: '/lp4',
  path: '/lp4',
  getParentRoute: () => StaticRoute,
} as any)
const StaticLp3Route = StaticLp3RouteImport.update({
  id: '/lp3',
  path: '/lp3',
  getParentRoute: () => StaticRoute,
} as any)
const StaticLp2Route = StaticLp2RouteImport.update({
  id: '/lp2',
  path: '/lp2',
  getParentRoute: () => StaticRoute,
} as any)
const StaticLp1Route = StaticLp1RouteImport.update({
  id: '/lp1',
  path: '/lp1',
  getParentRoute: () => StaticRoute,
} as any)
const StaticLpRoute = StaticLpRouteImport.update({
  id: '/lp',
  path: '/lp',
  getParentRoute: () => StaticRoute,
} as any)
const StaticDuckerwebRoute = StaticDuckerwebRouteImport.update({
  id: '/duckerweb',
  path: '/duckerweb',
  getParentRoute: () => StaticRoute,
} as any)
const AuthedGhcardsRoute = AuthedGhcardsRouteImport.update({
  id: '/ghcards',
  path: '/ghcards',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/ghcards': typeof AuthedGhcardsRoute
  '/duckerweb': typeof StaticDuckerwebRoute
  '/lp': typeof StaticLpRoute
  '/lp1': typeof StaticLp1Route
  '/lp2': typeof StaticLp2Route
  '/lp3': typeof StaticLp3Route
  '/lp4': typeof StaticLp4Route
  '/lp5': typeof StaticLp5Route
  '/privacy': typeof StaticPrivacyRoute
  '/terms-of-service': typeof StaticTermsOfServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/ghcards': typeof AuthedGhcardsRoute
  '/duckerweb': typeof StaticDuckerwebRoute
  '/lp': typeof StaticLpRoute
  '/lp1': typeof StaticLp1Route
  '/lp2': typeof StaticLp2Route
  '/lp3': typeof StaticLp3Route
  '/lp4': typeof StaticLp4Route
  '/lp5': typeof StaticLp5Route
  '/privacy': typeof StaticPrivacyRoute
  '/terms-of-service': typeof StaticTermsOfServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_static': typeof StaticRouteWithChildren
  '/share': typeof ShareRoute
  '/_authed/ghcards': typeof AuthedGhcardsRoute
  '/_static/duckerweb': typeof StaticDuckerwebRoute
  '/_static/lp': typeof StaticLpRoute
  '/_static/lp1': typeof StaticLp1Route
  '/_static/lp2': typeof StaticLp2Route
  '/_static/lp3': typeof StaticLp3Route
  '/_static/lp4': typeof StaticLp4Route
  '/_static/lp5': typeof StaticLp5Route
  '/_static/privacy': typeof StaticPrivacyRoute
  '/_static/terms-of-service': typeof StaticTermsOfServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/share'
    | '/ghcards'
    | '/duckerweb'
    | '/lp'
    | '/lp1'
    | '/lp2'
    | '/lp3'
    | '/lp4'
    | '/lp5'
    | '/privacy'
    | '/terms-of-service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/share'
    | '/ghcards'
    | '/duckerweb'
    | '/lp'
    | '/lp1'
    | '/lp2'
    | '/lp3'
    | '/lp4'
    | '/lp5'
    | '/privacy'
    | '/terms-of-service'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_static'
    | '/share'
    | '/_authed/ghcards'
    | '/_static/duckerweb'
    | '/_static/lp'
    | '/_static/lp1'
    | '/_static/lp2'
    | '/_static/lp3'
    | '/_static/lp4'
    | '/_static/lp5'
    | '/_static/privacy'
    | '/_static/terms-of-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  StaticRoute: typeof StaticRouteWithChildren
  ShareRoute: typeof ShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static/terms-of-service': {
      id: '/_static/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof StaticTermsOfServiceRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/privacy': {
      id: '/_static/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof StaticPrivacyRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/lp5': {
      id: '/_static/lp5'
      path: '/lp5'
      fullPath: '/lp5'
      preLoaderRoute: typeof StaticLp5RouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/lp4': {
      id: '/_static/lp4'
      path: '/lp4'
      fullPath: '/lp4'
      preLoaderRoute: typeof StaticLp4RouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/lp3': {
      id: '/_static/lp3'
      path: '/lp3'
      fullPath: '/lp3'
      preLoaderRoute: typeof StaticLp3RouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/lp2': {
      id: '/_static/lp2'
      path: '/lp2'
      fullPath: '/lp2'
      preLoaderRoute: typeof StaticLp2RouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/lp1': {
      id: '/_static/lp1'
      path: '/lp1'
      fullPath: '/lp1'
      preLoaderRoute: typeof StaticLp1RouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/lp': {
      id: '/_static/lp'
      path: '/lp'
      fullPath: '/lp'
      preLoaderRoute: typeof StaticLpRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/duckerweb': {
      id: '/_static/duckerweb'
      path: '/duckerweb'
      fullPath: '/duckerweb'
      preLoaderRoute: typeof StaticDuckerwebRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_authed/ghcards': {
      id: '/_authed/ghcards'
      path: '/ghcards'
      fullPath: '/ghcards'
      preLoaderRoute: typeof AuthedGhcardsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedGhcardsRoute: typeof AuthedGhcardsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedGhcardsRoute: AuthedGhcardsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface StaticRouteChildren {
  StaticDuckerwebRoute: typeof StaticDuckerwebRoute
  StaticLpRoute: typeof StaticLpRoute
  StaticLp1Route: typeof StaticLp1Route
  StaticLp2Route: typeof StaticLp2Route
  StaticLp3Route: typeof StaticLp3Route
  StaticLp4Route: typeof StaticLp4Route
  StaticLp5Route: typeof StaticLp5Route
  StaticPrivacyRoute: typeof StaticPrivacyRoute
  StaticTermsOfServiceRoute: typeof StaticTermsOfServiceRoute
}

const StaticRouteChildren: StaticRouteChildren = {
  StaticDuckerwebRoute: StaticDuckerwebRoute,
  StaticLpRoute: StaticLpRoute,
  StaticLp1Route: StaticLp1Route,
  StaticLp2Route: StaticLp2Route,
  StaticLp3Route: StaticLp3Route,
  StaticLp4Route: StaticLp4Route,
  StaticLp5Route: StaticLp5Route,
  StaticPrivacyRoute: StaticPrivacyRoute,
  StaticTermsOfServiceRoute: StaticTermsOfServiceRoute,
}

const StaticRouteWithChildren =
  StaticRoute._addFileChildren(StaticRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  StaticRoute: StaticRouteWithChildren,
  ShareRoute: ShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
