/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as StaticRouteImport } from './routes/_static'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaticTermsOfServiceRouteImport } from './routes/_static/terms-of-service'
import { Route as StaticPrivacyRouteImport } from './routes/_static/privacy'
import { Route as StaticDuckerwebRouteImport } from './routes/_static/duckerweb'
import { Route as AuthedGhcardsRouteImport } from './routes/_authed/ghcards'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticRoute = StaticRouteImport.update({
  id: '/_static',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticTermsOfServiceRoute = StaticTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => StaticRoute,
} as any)
const StaticPrivacyRoute = StaticPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => StaticRoute,
} as any)
const StaticDuckerwebRoute = StaticDuckerwebRouteImport.update({
  id: '/duckerweb',
  path: '/duckerweb',
  getParentRoute: () => StaticRoute,
} as any)
const AuthedGhcardsRoute = AuthedGhcardsRouteImport.update({
  id: '/ghcards',
  path: '/ghcards',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/ghcards': typeof AuthedGhcardsRoute
  '/duckerweb': typeof StaticDuckerwebRoute
  '/privacy': typeof StaticPrivacyRoute
  '/terms-of-service': typeof StaticTermsOfServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/ghcards': typeof AuthedGhcardsRoute
  '/duckerweb': typeof StaticDuckerwebRoute
  '/privacy': typeof StaticPrivacyRoute
  '/terms-of-service': typeof StaticTermsOfServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_static': typeof StaticRouteWithChildren
  '/share': typeof ShareRoute
  '/_authed/ghcards': typeof AuthedGhcardsRoute
  '/_static/duckerweb': typeof StaticDuckerwebRoute
  '/_static/privacy': typeof StaticPrivacyRoute
  '/_static/terms-of-service': typeof StaticTermsOfServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/share'
    | '/ghcards'
    | '/duckerweb'
    | '/privacy'
    | '/terms-of-service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/share'
    | '/ghcards'
    | '/duckerweb'
    | '/privacy'
    | '/terms-of-service'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_static'
    | '/share'
    | '/_authed/ghcards'
    | '/_static/duckerweb'
    | '/_static/privacy'
    | '/_static/terms-of-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  StaticRoute: typeof StaticRouteWithChildren
  ShareRoute: typeof ShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static/terms-of-service': {
      id: '/_static/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof StaticTermsOfServiceRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/privacy': {
      id: '/_static/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof StaticPrivacyRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/duckerweb': {
      id: '/_static/duckerweb'
      path: '/duckerweb'
      fullPath: '/duckerweb'
      preLoaderRoute: typeof StaticDuckerwebRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_authed/ghcards': {
      id: '/_authed/ghcards'
      path: '/ghcards'
      fullPath: '/ghcards'
      preLoaderRoute: typeof AuthedGhcardsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedGhcardsRoute: typeof AuthedGhcardsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedGhcardsRoute: AuthedGhcardsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface StaticRouteChildren {
  StaticDuckerwebRoute: typeof StaticDuckerwebRoute
  StaticPrivacyRoute: typeof StaticPrivacyRoute
  StaticTermsOfServiceRoute: typeof StaticTermsOfServiceRoute
}

const StaticRouteChildren: StaticRouteChildren = {
  StaticDuckerwebRoute: StaticDuckerwebRoute,
  StaticPrivacyRoute: StaticPrivacyRoute,
  StaticTermsOfServiceRoute: StaticTermsOfServiceRoute,
}

const StaticRouteWithChildren =
  StaticRoute._addFileChildren(StaticRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  StaticRoute: StaticRouteWithChildren,
  ShareRoute: ShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
